/**
 * ACHIEVEMENTS - Badge System
 * 38 active badges + 5 future badges (commented out)
 * Tracks user progress and spiritual commitment
 */

export const ACHIEVEMENTS = [
  // Category 1: The Consistency Chain (The Path of the Steadfast)
  {
    id: "al-mujawid",
    name: "Al-Mujawid",
    nameEn: "The Excellent Worshipper",
    description: "7-Day Streak",
    icon: "🟢",
    category: "consistency",
    rarity: "common",
    requirement: { type: "streak", count: 7 },
  },
  {
    id: "al-muqim",
    name: "Al-Muqim",
    nameEn: "The Steadfast",
    description: "30-Day Streak",
    icon: "🔵",
    category: "consistency",
    rarity: "rare",
    requirement: { type: "streak", count: 30 },
  },
  {
    id: "al-muhsin",
    name: "Al-Muhsin",
    nameEn: "The Virtuous Doer",
    description: "100-Day Streak",
    icon: "🟣",
    category: "consistency",
    rarity: "epic",
    requirement: { type: "streak", count: 100 },
  },
  {
    id: "al-abrar",
    name: "Al-Abrar",
    nameEn: "The Righteous",
    description: "365-Day Streak",
    icon: "🟡",
    category: "consistency",
    rarity: "legendary",
    requirement: { type: "streak", count: 365 },
  },

  // Special Milestone: Complete Collection
  {
    id: "dhikr-master",
    name: "Sayyid al-Dhakirin",
    nameEn: "Master of Remembrance",
    description: "Unlocked all 27 Zikr phrases",
    icon: "👑✨",
    category: "milestone",
    rarity: "legendary",
    requirement: { type: "unlocked", count: 27 },
  },

  // Category 2: The Path to Mastery - Subhanallah
  {
    id: "glorifier-1",
    name: "Al-Musabbih I",
    nameEn: "The Glorifier",
    description: 'Said "Subhanallah" 1,000 times',
    icon: "💎",
    category: "mastery",
    tier: 1,
    tierName: "Brass",
    rarity: "common",
    requirement: { type: "phrase_count", phraseId: 4, count: 1000 },
  },
  {
    id: "glorifier-2",
    name: "Al-Musabbih II",
    nameEn: "The Glorifier",
    description: 'Said "Subhanallah" 2,000 times',
    icon: "💎",
    category: "mastery",
    tier: 2,
    tierName: "Bronze",
    rarity: "common",
    requirement: { type: "phrase_count", phraseId: 4, count: 2000 },
  },
  {
    id: "glorifier-3",
    name: "Al-Musabbih Al-Kabir III",
    nameEn: "The Master Glorifier",
    description: 'Said "Subhanallah" 3,000 times',
    icon: "💎",
    category: "mastery",
    tier: 3,
    tierName: "Silver",
    rarity: "rare",
    requirement: { type: "phrase_count", phraseId: 4, count: 3000 },
  },
  {
    id: "glorifier-4",
    name: "Al-Musabbih Al-Mithali IV",
    nameEn: "The Exemplary Glorifier",
    description: 'Said "Subhanallah" 4,000 times',
    icon: "💎",
    category: "mastery",
    tier: 4,
    tierName: "Platinum",
    rarity: "epic",
    requirement: { type: "phrase_count", phraseId: 4, count: 4000 },
  },
  {
    id: "glorifier-5",
    name: "Al-Musabbih Al-Usstha V",
    nameEn: "The Legendary Glorifier",
    description: 'Said "Subhanallah" 5,000 times',
    icon: "💎",
    category: "mastery",
    tier: 5,
    tierName: "Gold",
    rarity: "legendary",
    requirement: { type: "phrase_count", phraseId: 4, count: 5000 },
  },

  // Path to Mastery - Allahu Akbar
  {
    id: "mukabbir-1",
    name: "Al-Mukabbir I",
    nameEn: "The One Who Magnifies",
    description: 'Said "Allahu Akbar" 1,000 times',
    icon: "👑",
    category: "mastery",
    tier: 1,
    tierName: "Brass",
    rarity: "common",
    requirement: { type: "phrase_count", phraseId: 3, count: 1000 },
  },
  {
    id: "mukabbir-2",
    name: "Al-Mukabbir II",
    nameEn: "The One Who Magnifies",
    description: 'Said "Allahu Akbar" 2,000 times',
    icon: "👑",
    category: "mastery",
    tier: 2,
    tierName: "Bronze",
    rarity: "common",
    requirement: { type: "phrase_count", phraseId: 3, count: 2000 },
  },
  {
    id: "mukabbir-3",
    name: "Al-Mukabbir Al-Kabir III",
    nameEn: "The Master Magnifier",
    description: 'Said "Allahu Akbar" 3,000 times',
    icon: "👑",
    category: "mastery",
    tier: 3,
    tierName: "Silver",
    rarity: "rare",
    requirement: { type: "phrase_count", phraseId: 3, count: 3000 },
  },
  {
    id: "mukabbir-4",
    name: "Al-Mukabbir Al-Mithali IV",
    nameEn: "The Exemplary Magnifier",
    description: 'Said "Allahu Akbar" 4,000 times',
    icon: "👑",
    category: "mastery",
    tier: 4,
    tierName: "Platinum",
    rarity: "epic",
    requirement: { type: "phrase_count", phraseId: 3, count: 4000 },
  },
  {
    id: "mukabbir-5",
    name: "Al-Mukabbir Al-Usstha V",
    nameEn: "The Legendary Magnifier",
    description: 'Said "Allahu Akbar" 5,000 times',
    icon: "👑",
    category: "mastery",
    tier: 5,
    tierName: "Gold",
    rarity: "legendary",
    requirement: { type: "phrase_count", phraseId: 3, count: 5000 },
  },

  // Path to Mastery - Alhamdulillah
  {
    id: "hammad-1",
    name: "Al-Hammad I",
    nameEn: "The One Who Praises",
    description: 'Said "Alhamdulillah" 1,000 times',
    icon: "🎁",
    category: "mastery",
    tier: 1,
    tierName: "Brass",
    rarity: "common",
    requirement: { type: "phrase_count", phraseId: 2, count: 1000 },
  },
  {
    id: "hammad-2",
    name: "Al-Hammad II",
    nameEn: "The One Who Praises",
    description: 'Said "Alhamdulillah" 2,000 times',
    icon: "🎁",
    category: "mastery",
    tier: 2,
    tierName: "Bronze",
    rarity: "common",
    requirement: { type: "phrase_count", phraseId: 2, count: 2000 },
  },
  {
    id: "hammad-3",
    name: "Al-Hammad Al-Kabir III",
    nameEn: "The Master Praiser",
    description: 'Said "Alhamdulillah" 3,000 times',
    icon: "🎁",
    category: "mastery",
    tier: 3,
    tierName: "Silver",
    rarity: "rare",
    requirement: { type: "phrase_count", phraseId: 2, count: 3000 },
  },
  {
    id: "hammad-4",
    name: "Al-Hammad Al-Mithali IV",
    nameEn: "The Exemplary Praiser",
    description: 'Said "Alhamdulillah" 4,000 times',
    icon: "🎁",
    category: "mastery",
    tier: 4,
    tierName: "Platinum",
    rarity: "epic",
    requirement: { type: "phrase_count", phraseId: 2, count: 4000 },
  },
  {
    id: "hammad-5",
    name: "Al-Hammad Al-Usstha V",
    nameEn: "The Legendary Praiser",
    description: 'Said "Alhamdulillah" 5,000 times',
    icon: "🎁",
    category: "mastery",
    tier: 5,
    tierName: "Gold",
    rarity: "legendary",
    requirement: { type: "phrase_count", phraseId: 2, count: 5000 },
  },

  // Path to Mastery - Astaghfirullah
  {
    id: "tawwab-1",
    name: "At-Tawwab I",
    nameEn: "The Repentant",
    description: 'Said "Astaghfirullah" 1,000 times',
    icon: "🤲",
    category: "mastery",
    tier: 1,
    tierName: "Brass",
    rarity: "common",
    requirement: { type: "phrase_count", phraseId: 5, count: 1000 },
  },
  {
    id: "tawwab-2",
    name: "At-Tawwab II",
    nameEn: "The Repentant",
    description: 'Said "Astaghfirullah" 2,000 times',
    icon: "🤲",
    category: "mastery",
    tier: 2,
    tierName: "Bronze",
    rarity: "common",
    requirement: { type: "phrase_count", phraseId: 5, count: 2000 },
  },
  {
    id: "tawwab-3",
    name: "At-Tawwab Al-Kabir III",
    nameEn: "The Master Repentant",
    description: 'Said "Astaghfirullah" 3,000 times',
    icon: "🤲",
    category: "mastery",
    tier: 3,
    tierName: "Silver",
    rarity: "rare",
    requirement: { type: "phrase_count", phraseId: 5, count: 3000 },
  },
  {
    id: "tawwab-4",
    name: "At-Tawwab Al-Mithali IV",
    nameEn: "The Exemplary Repentant",
    description: 'Said "Astaghfirullah" 4,000 times',
    icon: "🤲",
    category: "mastery",
    tier: 4,
    tierName: "Platinum",
    rarity: "epic",
    requirement: { type: "phrase_count", phraseId: 5, count: 4000 },
  },
  {
    id: "tawwab-5",
    name: "At-Tawwab Al-Usstha V",
    nameEn: "The Legendary Repentant",
    description: 'Said "Astaghfirullah" 5,000 times',
    icon: "🤲",
    category: "mastery",
    tier: 5,
    tierName: "Gold",
    rarity: "legendary",
    requirement: { type: "phrase_count", phraseId: 5, count: 5000 },
  },

  // Category 3: The Spiritual Voyage (Earning Your Divine Titles)
  {
    id: "al-mustaghfir",
    name: "Al-Mustaghfir",
    nameEn: "The Constant Seeker of Forgiveness",
    description: "Use all forgiveness-related phrases in a week",
    icon: "🤲",
    category: "spiritual",
    rarity: "rare",
    requirement: { type: "category_weekly", category: "forgiveness" },
  },
  {
    id: "ash-shakir",
    name: "Ash-Shakir",
    nameEn: "The Thankful One",
    description: "Reach Mastery Level II on Alhamdulillah phrases",
    icon: "🙏",
    category: "spiritual",
    rarity: "rare",
    requirement: { type: "mastery_level", phrases: [3, 15], level: 2 },
  },
  {
    id: "al-mutawakkil",
    name: "Al-Mutawakkil",
    nameEn: "The One Who Relies on God",
    description: 'Use "Hasbunallahu" phrases 500 times',
    icon: "🤝",
    category: "spiritual",
    rarity: "rare",
    requirement: { type: "phrase_count", phraseId: 8, count: 500 },
  },
  {
    id: "at-talib-ul-ilm",
    name: "At-Ṭālib ul-ʿIlm",
    nameEn: "The Seeker of Knowledge",
    description: 'Say "Rabbi Zidni Ilma" 500 times',
    icon: "📚",
    category: "spiritual",
    rarity: "rare",
    requirement: { type: "phrase_count", phraseId: 23, count: 500 },
  },
  {
    id: "ar-radi",
    name: "Ar-Rāḍī",
    nameEn: "The Content One",
    description: "Complete 7 sessions with perfect accuracy",
    icon: "😌",
    category: "spiritual",
    rarity: "epic",
    requirement: { type: "perfect_sessions", count: 7 },
  },
  {
    id: "al-muhtadi",
    name: "Al-Muhtadī",
    nameEn: "The Guided One",
    description: 'Say "Ihdinas Sirat" 100 times',
    icon: "🧭",
    category: "spiritual",
    rarity: "rare",
    requirement: { type: "phrase_count", phraseId: 21, count: 100 },
  },
  {
    id: "al-muraqib",
    name: "Al-Murāqib",
    nameEn: "The Mindful One",
    description: "Perform Zikr at 5 different times of day",
    icon: "⏰",
    category: "spiritual",
    rarity: "rare",
    requirement: { type: "time_diversity", count: 5 },
  },
  {
    id: "al-mudhakkir",
    name: "Al-Mudhakkir",
    nameEn: "The One Who Reminds",
    description: "Complete 20-minute session without missing",
    icon: "🔔",
    category: "immersive",
    rarity: "rare",
    requirement: { type: "session_duration", count: 1200 },
  },
  {
    id: "dhu-al-hijjatayn",
    name: "Dhū al-Hijjatayn",
    nameEn: "The One of Two Migrations",
    description: "Earn 1,000 points in a single day",
    icon: "🚀",
    category: "immersive",
    rarity: "epic",
    requirement: { type: "daily_points", count: 1000 },
  },

  // Category 4: The Secret & Serendipitous (Hidden Blessings)
  {
    id: "al-fatih",
    name: "Al-Fātih",
    nameEn: "The Opener",
    description: 'Say "Bismillah" as your very first phrase ever',
    icon: "🔑",
    category: "secret",
    rarity: "rare",
    requirement: { type: "first_phrase", phraseId: 1 },
  },
  {
    id: "al-lubb",
    name: "Al-Lubb",
    nameEn: "Night Intellect",
    description: "Perform Zikr during last third of night",
    icon: "🌙",
    category: "secret",
    rarity: "epic",
    requirement: { type: "night_session" },
  },
  {
    id: "al-khalish",
    name: "Al-Khālish",
    nameEn: "The Sincere",
    description: "Perform a 5-minute session with phone on silent",
    icon: "🤫",
    category: "secret",
    rarity: "rare",
    requirement: { type: "silent_session", count: 300 },
  },
  {
    id: "dhu-al-faqar",
    name: "Dhū al-Faqār",
    nameEn: "The One with the Distinction",
    description: "Unlock all other badges in the game",
    icon: "🎉",
    category: "secret",
    rarity: "legendary",
    requirement: { type: "all_badges" },
  },

  // ============================================================================
  // 🔮 FUTURE ACHIEVEMENTS (COMMENTED OUT)
  // ============================================================================
  // Uncomment these when you want to add La ilaha illallah mastery tracking!
  // These were suggested by Claude but not in the original app.
  //
  // NOTE: phraseId 27 = "La ilaha illallah"
  // ============================================================================

  // // Path to Mastery - La ilaha illallah (The Shahada)
  // {
  //   id: 'muwahhid-1',
  //   name: 'Al-Muwahhid I',
  //   nameEn: 'The Monotheist',
  //   description: 'Said "La ilaha illallah" 1,000 times',
  //   icon: '☪️',
  //   category: 'mastery',
  //   tier: 1,
  //   tierName: 'Brass',
  //   rarity: 'common',
  //   requirement: { type: 'phrase_count', phraseId: 27, count: 1000 }
  // },
  // {
  //   id: 'muwahhid-2',
  //   name: 'Al-Muwahhid II',
  //   nameEn: 'The Monotheist',
  //   description: 'Said "La ilaha illallah" 2,000 times',
  //   icon: '☪️',
  //   category: 'mastery',
  //   tier: 2,
  //   tierName: 'Bronze',
  //   rarity: 'common',
  //   requirement: { type: 'phrase_count', phraseId: 27, count: 2000 }
  // },
  // {
  //   id: 'muwahhid-3',
  //   name: 'Al-Muwahhid Al-Kabir III',
  //   nameEn: 'The Master Monotheist',
  //   description: 'Said "La ilaha illallah" 3,000 times',
  //   icon: '☪️',
  //   category: 'mastery',
  //   tier: 3,
  //   tierName: 'Silver',
  //   rarity: 'rare',
  //   requirement: { type: 'phrase_count', phraseId: 27, count: 3000 }
  // },
  // {
  //   id: 'muwahhid-4',
  //   name: 'Al-Muwahhid Al-Mithali IV',
  //   nameEn: 'The Exemplary Monotheist',
  //   description: 'Said "La ilaha illallah" 4,000 times',
  //   icon: '☪️',
  //   category: 'mastery',
  //   tier: 4,
  //   tierName: 'Platinum',
  //   rarity: 'epic',
  //   requirement: { type: 'phrase_count', phraseId: 27, count: 4000 }
  // },
  // {
  //   id: 'muwahhid-5',
  //   name: 'Al-Muwahhid Al-Usstha V',
  //   nameEn: 'The Legendary Monotheist',
  //   description: 'Said "La ilaha illallah" 5,000 times',
  //   icon: '☪️',
  //   category: 'mastery',
  //   tier: 5,
  //   tierName: 'Gold',
  //   rarity: 'legendary',
  //   requirement: { type: 'phrase_count', phraseId: 27, count: 5000 }
  // },
  // Category 4: SECRET ACHIEVEMENTS (The Path of the True Seeker)
  // {
  //   id: "hidden-gem",
  //   name: "Jawhar al-Makhfi",
  //   nameEn: "The Hidden Gem",
  //   description: "Discovered a secret phrase",
  //   icon: "💠",
  //   category: "secret",
  //   rarity: "epic",
  //   requirement: { type: "secret_phrase" },
  // },
  // {
  //   id: "perfect-completion",
  //   name: "Al-Kamal",
  //   nameEn: "The Perfect",
  //   description: "Completed every achievement",
  //   icon: "🎉",
  //   category: "secret",
  //   rarity: "legendary",
  //   requirement: { type: "all_badges" },
  // },
];
